spring.application.name=fullstackproject1

spring.datasource.url=jdbc:postgresql://localhost:5432/fp_1
spring.datasource.username=postgres
spring.datasource.password=admin@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.open-in-view=false